[package]
name = "payment-system"
version = "0.1.0"
description = "Payment system with periodic payments, billing, and profit distribution"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "payment_system"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "~1.16.0"
sha3 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
