[package]
name = "delegation-management"
version = "0.1.0"
description = "Bank delegation to AI policy management smart contract"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "delegation_management"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
spl-token = { workspace = true }
spl-memo = { workspace = true }
solana-program = { workspace = true }
sha3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
